// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGybNp7RRU9xVVKQujSAqOnQaBayFbx2k',
    appId: '1:764974074282:web:a999f4f21fc122ad4043d3',
    messagingSenderId: '764974074282',
    projectId: 'flut-fire-chat-ap',
    authDomain: 'flut-fire-chat-ap.firebaseapp.com',
    storageBucket: 'flut-fire-chat-ap.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIKmLgiGjE9iBd97yjZT6fjJgrwUFMcZQ',
    appId: '1:764974074282:android:7493e053fae386ab4043d3',
    messagingSenderId: '764974074282',
    projectId: 'flut-fire-chat-ap',
    storageBucket: 'flut-fire-chat-ap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjTve6ihEH63GHt7lExVzm9reF_HoriqM',
    appId: '1:764974074282:ios:1c2f596d02e99e1b4043d3',
    messagingSenderId: '764974074282',
    projectId: 'flut-fire-chat-ap',
    storageBucket: 'flut-fire-chat-ap.appspot.com',
    iosBundleId: 'com.example.chatappFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjTve6ihEH63GHt7lExVzm9reF_HoriqM',
    appId: '1:764974074282:ios:42126e13e12040c84043d3',
    messagingSenderId: '764974074282',
    projectId: 'flut-fire-chat-ap',
    storageBucket: 'flut-fire-chat-ap.appspot.com',
    iosBundleId: 'com.example.chatappFlutter.RunnerTests',
  );
}
